spring:
  datasource:
    url: jdbc:mysql://117.50.163.4:3306/dy_movies?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jdy200255
server:
  port: 80

logging:
  level:
    xyz.jdynb.dymovies.mapper: trace