server:
  # 生产环境运行端口
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://117.50.163.4:3306/dy_movies?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            skipUpdateCheck: false # 跳过更新检查。生产部署要禁止

# 配置日志信息
logging:
  file:
    name: server.log
