server:
  # 本地开发使用 80 端口
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dy_movies?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
logging:
  level:
    xyz.jdynb.dymovies.mapper: trace
    xyz.jdynb.dymovies.admin.mapper: trace